# Generated by Django 5.1 on 2024-08-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='discount',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offers',
            name='timings',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
